# SpeedrunnerSwap Configuration
# Version 2.1

# Teams Configuration
teams:
  runners: []  # List of runner player names
  hunters: []  # List of hunter player names

# Swap System Configuration
swap:
  # Fixed interval or random swap with Gaussian jitter
  randomize: false
  # Base interval in seconds (or mean if randomized)
  interval: 60
  # Enable experimental intervals (<30s and >max) via GUI toggle
  beta_enabled: true
  # Apply per-mode default interval when switching modes (if game not running)
  apply_default_on_mode_switch: true
  # Min and max interval in seconds (only used if randomize is true)
  min_interval: 30
  max_interval: 90
  # Per-mode default intervals
  default_intervals:
    dream: 60
    sapnap: 60
  # Jitter settings (only used if randomize is true)
  jitter:
    # Standard deviation in seconds
    stddev: 15
    # Whether to clamp within min/max limits
    clamp: true
  # Grace period after swaps (in ticks, 20 ticks = 1 second)
  grace_period_ticks: 40
  # Auto-pause if a runner disconnects
  pause_on_disconnect: true
  # If true, apply the final active runner's state to all runners when ending the game
  preserve_runner_progress_on_end: false
  hunter_swap:
    enabled: false
    interval: 60
  hot_potato_mode:
    enabled: false

# Safe Swap Configuration
safe_swap:
  # Whether to enable safe swap feature
  enabled: false
  # Horizontal scan radius (blocks)
  horizontal_radius: 5
  # Vertical scan distance (blocks)
  vertical_distance: 10
  # Dangerous blocks to avoid (material names)
  dangerous_blocks:
    - LAVA
    - MAGMA_BLOCK
    - CACTUS
    - CAMPFIRE
    - FIRE
    - SOUL_FIRE
    - SOUL_CAMPFIRE
    - POINTED_DRIPSTONE

# Freeze Mode for Inactive Runners
# Options: EFFECTS, SPECTATOR, LIMBO, CAGE
freeze_mode: CAGE

# Limbo configuration
limbo:
  world: "world"
  x: 0.5
  y: 200.0
  z: 0.5

# Movement and Interaction Control
cancel:
  # Cancel movement for inactive runners
  movement: true
  # Cancel interactions for inactive runners
  interactions: true

# Tracker Configuration
tracker:
  # Whether to enable the compass tracker
  enabled: true
  # How often to update the compass (in ticks, 20 ticks = 1 second)
  update_ticks: 20
  # Temporary compass jamming after swaps to give the new runner an escape window
  compass_jamming:
    enabled: false
    # Duration of compass jamming in ticks (20 ticks = 1 second)
    duration_ticks: 100
    # Max random offset (in blocks) for jammed compass target
    max_jam_distance: 500

# GUI Configuration
gui:
  main_menu:
    title: "SpeedrunnerSwap Menu"
    rows: 3
  team_selector:
    title: "Team Selector"
    rows: 4
  settings:
    title: "Settings"
    rows: 5

# Broadcast Configuration
broadcasts:
  # Whether to broadcast swap events to all players
  enabled: true
  # Whether to broadcast game start/stop events
  game_events: true
  # Whether to broadcast team changes
  team_changes: true

# Freeze Mechanic Configuration
freeze_mechanic:
  enabled: false
  duration_ticks: 100  # 5 seconds
  check_interval_ticks: 20
  max_distance: 50

# Timer Visibility Configuration
timer_visibility:
  # Whether active runners see the timer
  runner_visibility: "last_10"  # Options: "always", "last_10", "never"
  # Whether waiting runners see the timer
  waiting_visibility: "always"  # Options: "always", "last_10", "never"
  # Whether hunters see the timer
  hunter_visibility: "never"    # Options: "always", "last_10", "never"

# UI update frequency (performance tuning)
ui:
  update_ticks:
    # How often to update the actionbar for timers (in ticks)
    actionbar: 20
    # How often to update titles for waiting runners (in ticks)
    title: 10

# Simple Voice Chat Integration (if available)
voice_chat:
  # Whether to integrate with Simple Voice Chat
  enabled: false
  # Whether to mute inactive runners
  mute_inactive_runners: true

# Single Player Sleep Configuration
single_player_sleep:
  # If enabled, only the active runner can sleep to skip night
  # This helps when other players are caged or frozen and can't sleep
  # Enabled by default for Sapnap mode, disabled by default for Dreams mode
  enabled: false

# Power-ups Configuration
power_ups:
  enabled: false
  good_effects:
    - SPEED
    - DOLPHINS_GRACE
    - REGENERATION
    - NIGHT_VISION
    - ABSORPTION
  bad_effects:
    - SLOWNESS
    - WEAKNESS
    - HUNGER
    - DARKNESS
    - GLOWING

# Last Stand Configuration
last_stand:
  enabled: false
  duration_ticks: 600 # 30 seconds
  strength_amplifier: 1
  speed_amplifier: 1

# Kits Configuration
# Note: Kits are configured in kits.yml
kits:
  enabled: false  # Controls whether the kit system is enabled

# Advanced Stats Configuration
stats:
  enabled: true
  # How often to update distance traveled (in ticks)
  distance_update_ticks: 20
  # Whether to display stats periodically during the game
  periodic_display: false
  periodic_display_interval: 300 # 5 minutes

# World Border Configuration
world_border:
  enabled: false
  initial_size: 2000
  final_size: 100
  # Time in seconds for the border to shrink
  shrink_duration: 1800 # 30 minutes
  warning_distance: 50
  # How often to display border warnings (in seconds)
  warning_interval: 300 # 5 minutes

# Bounty System Configuration
bounty:
  enabled: false
  # Minimum time between bounties (in seconds)
  cooldown: 300
  # Duration of the glowing effect on the target (in seconds)
  glow_duration: 300
  # Rewards for successful bounty completion
  rewards:
    strength_duration: 300 # 5 minutes
    speed_duration: 300 # 5 minutes

# Sudden Death Configuration
sudden_death:
  enabled: false
  # Time before sudden death activates (in seconds)
  activation_delay: 1200 # 20 minutes
  # Effects given to players in sudden death
  effects:
    resistance_duration: 200
    regeneration_duration: 200
  # Coordinates for the sudden death arena in The End
  arena:
    x: 100
    y: 50
    z: 0
    # Maximum distance for random compass pointing when jammed
    max_jam_distance: 100

# Donation / Support
donation:
  # URL used for the clickable donate message shown when the game ends
  url: "https://donate.stripe.com/8x29AT0H58K03judnR0Ba01"

# Task Manager Configuration
task_manager:
  # Custom tasks that players can add to the task pool
  # Each task needs a unique ID and description
  custom_tasks:
    # Example custom tasks - add your own below!
    # - id: "build_wool_rainbow"
    #   description: "Build a rainbow using all 16 colors of wool"
    # - id: "survive_night_no_shelter"
    #   description: "Survive an entire night without any shelter or armor"
    # - id: "collect_100_flowers"
    #   description: "Collect 100 flowers of any type"
  # Whether to include default built-in tasks
  include_default_tasks: true
  # Maximum time for a task game (in minutes, 0 = no limit)
  max_game_duration: 0
  # Disconnect/rejoin behavior
  pause_on_disconnect: true
  rejoin_grace_seconds: 180
  remove_on_timeout: true
  allow_late_joiners: false
  end_when_one_left: false
  # Runtime state (do not edit manually unless you know what you're doing)
  runtime:
    assignments: {}
    disconnect_times: {}

# General game settings
game:
  # Default mode selected on server start: dream | sapnap | task
  default_mode: dream
