name: SpeedrunnerSwap
version: '${project.version}'
main: com.example.speedrunnerswap.SpeedrunnerSwap
api-version: '1.21'
authors: [muj3b]
description: |
  Dream-style "Speedrunner Swap" challenge where speedrunners share the same state and swap control on a timer.
  Features include:
  - Random power-ups on swap
  - Last Stand mode for final runner
  - Custom kits for runners and hunters
  - Configurable swap intervals
  - Safe swap locations
  - Hunter swap system
  - Compass tracking system
website: https://github.com/muj3b/minecraft-speedrunner-swap-plugin

# Ensure we load after voice chat plugins if present
softdepend: [SimpleVoiceChat, voicechat]

commands:
  swap:
    description: Control Speedrunner Swap
    usage: /<command>
    permission: speedrunnerswap.admin
    
permissions:
  speedrunnerswap.admin:
    default: op
    description: Full control over Speedrunner Swap plugin features
  speedrunnerswap.command:
    default: op
    description: General access to view status/GUI where allowed
